---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-rps-ui
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-rps-ui
  template:
    metadata:
      labels:
        name: pttg-rps-ui
        version: {{.VERSION}}
    spec:
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-rps-ui.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-residence-proving-ui,fmt=bundle
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.1.5
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '9000'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/pttg-residence-proving-ui-bundle.pem
          - name: SERVER_KEY
            value: /etc/nginx/secrets/pttg-residence-proving-ui-key.pem
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v1.2.7
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_DISCOVERY_URL
          - name: PROXY_REDIRECTION_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_REDIRECTION_URL
        args:
          - --config=/etc/secrets/keycloak-api-secret.yaml
          - --client-id=pttg-rps-{{.ENVIRONMENT}}
          - --listen=127.0.0.1:9000
          - --log-requests=true
          - --json-logging=true
          - --upstream-url=http://127.0.0.1:8000
          - --no-redirects=false
          - --cors-origins='*'
          - --resource=uri=/healthz|white-listed=true
          - --resource=uri=/|methods=GET,POST|roles=pttg-rps
          - --secure-cookie=true
          - --verbose
        imagePullPolicy: Always
        ports:
          - name: keycloak-http
            containerPort: 9000
        volumeMounts:
        - name: keycloak-api-secret
          mountPath: /etc/secrets
          readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
      - name: pttg-rps-ui
        image: quay.io/ukhomeofficedigital/pttg-rps-ui:{{.VERSION}}
        env:
          - name: API_ROOT
            value: "https://pttg-rps-api.pt-i-{{.ENVIRONMENT}}.svc.cluster.local"
          - name: CA_CERTS_PATH
            value: "/data/pttg-residence-proving-ui-ca.pem"
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: secrets
            readOnly: true
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: keycloak-api-secret
        secret:
          secretName: keycloak-api-secret
