---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
  name: pttg-rps-ui
spec:
  rules:
  - host: rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: pttg-rps-ui
          servicePort: 443
        path: /
  - host: pttg-rps-ui-{{.ENVIRONMENT}}.notprod.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: pttg-rps-ui
          servicePort: 443
        path: /
  tls:
  - hosts:
    - rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    - pttg-rps-ui-{{.ENVIRONMENT}}.notprod.homeoffice.gov.uk
    secretName: letsencrypt-pttg-rps-ui-tls
